dist: bionic
language: node_js
node_js:
  - 10
before_install:
    sudo apt-get install gobject-introspection libgirepository1.0-dev libcairo2 libcairo2-dev libgtk-3-dev libgtk-3.0 xvfb
install:
    make install
script:
    Xvfb :7 -screen 0 1024x768x16 &
    DISPLAY=:7 make check
